# -*- coding:utf-8 -*-
from Public.BaseService import *
from Public.Common import *

_common = Common()
ConfigObj: dict = _common.ReadJsonFile(path[0] + '/config.json')


class Lang(BaseService):

    def __init__(self):
        super().__init__()
        self.Type = str.lower(ConfigObj['Lang'])

        if self.Type == 'en':
            self.ManagerLogin = 'manager login'
            self.TeacherLogin = 'teacher login'
            self.ExamineeLogin = 'Examinee login'
            self.Back = 'Back'
            self.Exam = 'Take an exam'
            self.PracticeQuestions = 'Practice questions'
            self.LoginStudentID = 'Login with your student ID number'
            self.LoginWithAdmission = 'Login with your admission ticket number'
            self.StudentIDNumber = 'Student ID number'
            self.AdmissionTicketNumber = 'Admission ticket number'
            self.Login = 'Login'
            self.Start = 'Start'
            self.ChooseExamSubjects = 'Choose exam subjects'
            self.SelectTestQuestionType = 'Select test question type'
            self.MultipleChoiceQuestions = 'Multiple choice questions'
            self.TrueOrFalse = 'True or False'
            self.MultipleChoices = 'Multiple choices'
            self.FillInTheBlank = 'Fill in the blank'
            self.QuestionsAndAnswers = 'Questions and Answers'
            self.ProgrammingQuestions = 'Programming questions'
            self.DragAndDrop = 'Drag and drop'
            self.ConnectingQuestion = 'Connecting question'

            self.AdministratorAccount = 'Administrator account'
            self.Password = 'Password'
            self.Manager = 'Manager'
            self.Teacher = 'Teacher'
            self.Class = 'Class'
            self.Examinee = 'Examinee'
            self.RegistrationData = 'Registration data'
            self.Subject = 'Subject'
            self.KnowledgePoint = 'Knowledge point'
            self.Headline = 'Headline'
            self.TestQuestion = 'Test question'
            self.TestPaper = 'Test paper'
            self.TestPaperRules = 'Test paper rules'
            self.AnswerSheet = 'Answer sheet'
            self.SystemLog = 'System log'
            self.ExamLog = 'Exam log'
            self.Exit = 'Exit'

            self.Name = 'Name'

        elif self.Type == 'zh-cn':
            self.ManagerLogin = '管理员登录'
            self.TeacherLogin = '教师登录'
            self.ExamineeLogin = '考生登录'
            self.Back = '返回'
            self.Exam = '考试'
            self.PracticeQuestions = '练习题'
            self.LoginStudentID = '使用您的学生证号码登录'
            self.LoginWithAdmission = '使用您的准考证号码登录'
            self.StudentIDNumber = '学生证号码'
            self.AdmissionTicketNumber = '准考证号码'
            self.Login = '登录'
            self.Start = '开始'
            self.ChooseExamSubjects = '选择考试科目'
            self.SelectTestQuestionType = '选择试题类型'
            self.MultipleChoiceQuestions = '单项选择题'
            self.TrueOrFalse = '判断题'
            self.MultipleChoices = '多项选择题'
            self.FillInTheBlank = '填空题'
            self.QuestionsAndAnswers = '问答题'
            self.ProgrammingQuestions = '编程题'
            self.DragAndDrop = '拖拽题'
            self.ConnectingQuestion = '连线题'

            self.AdministratorAccount = '管理员账号'
            self.Password = '密码'
            self.Manager = '管理员'
            self.Teacher = '教师'
            self.Class = '班级'
            self.Examinee = '考生'
            self.RegistrationData = '报名'
            self.Subject = '科目'
            self.KnowledgePoint = '知识点'
            self.Headline = '大标题'
            self.TestQuestion = '试题'
            self.TestPaper = '试卷'
            self.TestPaperRules = '试卷规则'
            self.AnswerSheet = '答题卡'
            self.SystemLog = '系统日志'
            self.ExamLog = '考试日志'
            self.Exit = '退出'

            self.Name = '姓名'

        else:
            self.ManagerLogin = ''
            self.TeacherLogin = ''
            self.ExamineeLogin = ''
            self.Back = ''
            self.Exam = ''
            self.PracticeQuestions = ''
            self.LoginStudentID = ''
            self.LoginWithAdmission = ''
            self.StudentIDNumber = ''
            self.AdmissionTicketNumber = ''
            self.Login = ''
            self.Start = ''
            self.ChooseExamSubjects = ''
            self.SelectTestQuestionType = ''
            self.MultipleChoiceQuestions = ''
            self.TrueOrFalse = ''
            self.MultipleChoices = ''
            self.FillInTheBlank = ''
            self.QuestionsAndAnswers = ''
            self.ProgrammingQuestions = ''
            self.DragAndDrop = ''
            self.ConnectingQuestion = ''

            self.AdministratorAccount = ''
            self.Password = ''
            self.Manager = ''
            self.Teacher = ''
            self.Class = ''
            self.Examinee = ''
            self.RegistrationData = ''
            self.Subject = ''
            self.KnowledgePoint = ''
            self.Headline = ''
            self.TestQuestion = ''
            self.TestPaper = ''
            self.TestPaperRules = ''
            self.AnswerSheet = ''
            self.SystemLog = ''
            self.ExamLog = ''
            self.Exit = ''

            self.Name = ''