# -*- coding:utf-8 -*-
from Public.BaseService import *
from Public.Cache import *

_cache = Cache()


class Lang(BaseService):

    def __init__(self):
        super().__init__()
        self.Type = str.lower(_cache.Get('Lang'))

        if self.Type == 'en':
            self.ManagerLogin = 'manager login'
            self.TeacherLogin = 'teacher login'
            self.ExamineeLogin = 'Examinee login'
            self.Back = 'Back'
            self.Exam = 'Take an exam'
            self.PracticeQuestions = 'Practice questions'
            self.LoginStudentID = 'Login with your student ID number'
            self.LoginWithAdmission = 'Login with your admission ticket number'
            self.StudentIDNumber = 'Student ID number'
            self.AdmissionTicketNumber = 'Admission ticket number'
            self.Login = 'Login'
            self.Start = 'Start'
            self.ChooseExamSubjects = 'Choose exam subjects'
            self.SelectTestQuestionType = 'Select test question type'
            self.MultipleChoiceQuestions = 'Multiple choice questions'
            self.TrueOrFalse = 'True or False'
            self.MultipleChoices = 'Multiple choices'
            self.FillInTheBlank = 'Fill in the blank'
            self.QuestionsAndAnswers = 'Questions and Answers'
            self.ProgrammingQuestions = 'Programming questions'
            self.DragAndDrop = 'Drag and drop'
            self.ConnectingQuestion = 'Connecting question'

            self.ManageristratorAccount = 'Manageristrator account'
            self.Password = 'Password'
            self.Manager = 'Manager'
            self.Teacher = 'Teacher'
            self.Class = 'Class'
            self.Examinee = 'Examinee'
            self.RegistrationData = 'Registration data'
            self.Subject = 'Subject'
            self.KnowledgePoint = 'Knowledge point'
            self.Headline = 'Headline'
            self.TestQuestion = 'Test question'
            self.TestPaper = 'Test paper'
            self.TestPaperRules = 'Test paper rules'
            self.AnswerSheet = 'Answer sheet'
            self.SystemLog = 'System log'
            self.ExamLog = 'Exam log'
            self.Exit = 'Exit'
            self.CurrentPage = 'Current page'
            self.TotalPages = 'Total pages'
            self.PreviousPage = 'Previous page'
            self.NextPage = 'Next page'
            self.EnterPageNumber = 'Enter page number'
            self.EnterTheNumberOfLines = 'Enter the number of lines'
            self.Search = 'Search'
            self.Confirm = 'Confirm'
            self.Delete = 'Delete'
            self.Refresh = 'Refresh'
            self.Normal = 'Normal'
            self.Disable = 'Disable'
            self.Disabled = 'Disabled'
            self.CreationTime = 'Creation time'
            self.UpdateTime = 'Update time'
            self.ChangePassword = 'Change Password'

            self.Name = 'Name'
            self.NewManageristrator = 'New manager'
            self.ManagerDetails = 'Manager details'
            self.ManagerStatus = 'Manager status'

        elif self.Type == 'zh-cn':
            self.ManagerLogin = '管理员登录'
            self.TeacherLogin = '教师登录'
            self.ExamineeLogin = '考生登录'
            self.Back = '返回'
            self.Exam = '考试'
            self.PracticeQuestions = '练习题'
            self.LoginStudentID = '使用您的学生证号码登录'
            self.LoginWithAdmission = '使用您的准考证号码登录'
            self.StudentIDNumber = '学生证号码'
            self.AdmissionTicketNumber = '准考证号码'
            self.Login = '登录'
            self.Start = '开始'
            self.ChooseExamSubjects = '选择考试科目'
            self.SelectTestQuestionType = '选择试题类型'
            self.MultipleChoiceQuestions = '单项选择题'
            self.TrueOrFalse = '判断题'
            self.MultipleChoices = '多项选择题'
            self.FillInTheBlank = '填空题'
            self.QuestionsAndAnswers = '问答题'
            self.ProgrammingQuestions = '编程题'
            self.DragAndDrop = '拖拽题'
            self.ConnectingQuestion = '连线题'

            self.ManageristratorAccount = '管理员账号'
            self.Password = '密码'
            self.Manager = '管理员'
            self.Teacher = '教师'
            self.Class = '班级'
            self.Examinee = '考生'
            self.RegistrationData = '报名'
            self.Subject = '科目'
            self.KnowledgePoint = '知识点'
            self.Headline = '大标题'
            self.TestQuestion = '试题'
            self.TestPaper = '试卷'
            self.TestPaperRules = '试卷规则'
            self.AnswerSheet = '答题卡'
            self.SystemLog = '系统日志'
            self.ExamLog = '考试日志'
            self.Exit = '退出'
            self.CurrentPage = '当前页码'
            self.TotalPages = '总页码数'
            self.PreviousPage = '上一页'
            self.NextPage = '下一页'
            self.EnterPageNumber = '输入页码'
            self.EnterTheNumberOfLines = '输入行数'
            self.Search = '搜索'
            self.Confirm = '确认'
            self.Delete = '删除'
            self.Refresh = '刷新'
            self.Normal = '正常'
            self.Disable = '禁用'
            self.Disabled = '已禁用'
            self.CreationTime = '创建时间'
            self.UpdateTime = '更新时间'
            self.ChangePassword = '修改密码'

            self.Name = '姓名'
            self.NewManageristrator = '新建管理员'
            self.ManagerDetails = '管理员详情'
            self.ManagerStatus = '管理员状态'

        else:
            self.ManagerLogin = ''
            self.TeacherLogin = ''
            self.ExamineeLogin = ''
            self.Back = ''
            self.Exam = ''
            self.PracticeQuestions = ''
            self.LoginStudentID = ''
            self.LoginWithAdmission = ''
            self.StudentIDNumber = ''
            self.AdmissionTicketNumber = ''
            self.Login = ''
            self.Start = ''
            self.ChooseExamSubjects = ''
            self.SelectTestQuestionType = ''
            self.MultipleChoiceQuestions = ''
            self.TrueOrFalse = ''
            self.MultipleChoices = ''
            self.FillInTheBlank = ''
            self.QuestionsAndAnswers = ''
            self.ProgrammingQuestions = ''
            self.DragAndDrop = ''
            self.ConnectingQuestion = ''

            self.ManageristratorAccount = ''
            self.Password = ''
            self.Manager = ''
            self.Teacher = ''
            self.Class = ''
            self.Examinee = ''
            self.RegistrationData = ''
            self.Subject = ''
            self.KnowledgePoint = ''
            self.Headline = ''
            self.TestQuestion = ''
            self.TestPaper = ''
            self.TestPaperRules = ''
            self.AnswerSheet = ''
            self.SystemLog = ''
            self.ExamLog = ''
            self.Exit = ''
            self.CurrentPage = ''
            self.TotalPages = ''
            self.PreviousPage = ''
            self.NextPage = ''
            self.EnterPageNumber = ''
            self.EnterTheNumberOfLines = ''
            self.Search = ''
            self.Confirm = ''
            self.Delete = ''
            self.Refresh = ''
            self.Normal = ''
            self.Disable = ''
            self.Disabled = ''
            self.CreationTime = ''
            self.UpdateTime = ''
            self.ChangePassword = ''

            self.Name = ''
            self.NewManageristrator = ''
            self.ManagerDetails = ''
            self.ManagerStatus = ''