# -*- coding:utf-8 -*-
from Public.BaseService import *
from Public.Cache import *

_cache = Cache()


class Lang(BaseService):

    def __init__(self):
        super().__init__()
        self.Type = str.lower(_cache.Get('Lang'))

        if self.Type == 'en':
            self.ManagerLogin = 'manager login'
            self.TeacherLogin = 'teacher login'
            self.ExamineeLogin = 'Examinee login'
            self.Back = 'Back'
            self.Exam = 'Take an exam'
            self.PracticeQuestions = 'Practice questions'
            self.LoginStudentID = 'Login with your student ID number'
            self.LoginWithAdmission = 'Login with your admission ticket number'
            self.StudentIDNumber = 'Student ID number'
            self.AdmissionTicketNumber = 'Admission ticket number'
            self.Login = 'Login'
            self.Start = 'Start'
            self.ChooseExamSubjects = 'Choose exam subjects'
            self.SelectTestQuestionType = 'Select test question type'
            self.MultipleChoiceQuestions = 'Multiple choice questions'
            self.TrueOrFalse = 'True or False'
            self.MultipleChoices = 'Multiple choices'
            self.FillInTheBlank = 'Fill in the blank'
            self.QuestionsAndAnswers = 'Questions and Answers'
            self.ProgrammingQuestions = 'Programming questions'
            self.DragAndDrop = 'Drag and drop'
            self.ConnectingQuestion = 'Connecting question'

            self.ManageristratorAccount = 'Manageristrator account'
            self.Password = 'Password'
            self.Manager = 'Manager'
            self.Teacher = 'Teacher'
            self.Class = 'Class'
            self.Examinee = 'Examinee'
            self.RegistrationData = 'Registration data'
            self.HistoryRegistration = 'History registration data'
            self.Subject = 'Subject'
            self.KnowledgePoint = 'Knowledge point'
            self.Headline = 'Headline'
            self.TestQuestion = 'Test question'
            self.TestPaper = 'Test paper'
            self.TestPaperRules = 'Test paper rules'
            self.AnswerSheet = 'Answer sheet'
            self.SystemLog = 'System log'
            self.ExamLog = 'Exam log'
            self.Exit = 'Exit'
            self.CurrentPage = 'Current page'
            self.TotalPages = 'Total pages'
            self.PreviousPage = 'Previous page'
            self.NextPage = 'Next page'
            self.EnterPageNumber = 'Enter page number'
            self.EnterTheNumberOfLines = 'Enter the number of lines'
            self.Search = 'Search'
            self.Confirm = 'Confirm'
            self.Delete = 'Delete'
            self.Refresh = 'Refresh'
            self.Normal = 'Normal'
            self.Disable = 'Disable'
            self.Disabled = 'Disabled'
            self.CreationTime = 'Creation time'
            self.UpdateTime = 'Update time'
            self.ChangePassword = 'Change Password'
            self.Description = 'Description'
            self.Yes = 'Yes'
            self.No = 'No'
            self.NoDataAvailable = 'No data available'
            self.Submit = 'Submit'
            self.OperationFailed = 'Operation failed'

            self.Name = 'Name'
            self.NewManager = 'New manager'
            self.ManagerDetails = 'Manager details'
            self.ManagerStatus = 'Manager status'

            self.NewTeacher = 'New teacher'
            self.TeacherDetails = 'Teacher details'
            self.TeacherStatus = 'Teacher status'
            self.TeacherAccount = 'Teacher account'

            self.ClassName = 'Class name'
            self.NewClass = 'New class'
            self.ClassDetails = 'Class details'
            self.ClassCode = 'Class code'

            self.NewExaminee = 'New examinee'
            self.Contact = 'Contact'
            self.ExamineeNo = 'Examinee No.'
            self.ExamineeDetails = 'Examinee details'

            self.NewRegistration = 'New registration'
            self.ImportRegistration = 'Import registration'
            self.RegistrationDetails = 'Registration Details'
            self.RegisterInformation = 'Register information'
            self.ExamNo = 'Exam No.'
            self.TotalScore = 'Total score'
            self.PassLine = 'Pass line'
            self.ActualScore = 'Actual score'
            self.ExamDuration = 'Exam duration'
            self.StartTime = 'Start time'
            self.EndTime = 'End time'
            self.ActualDuration = 'Actual duration'
            self.PassStatus = 'Pass status'
            self.ExamState = 'Exam state'
            self.ExamType = 'Exam type'
            self.NoAnswerSheet = 'No answer sheet'
            self.WaitForVerification = 'Wait for verification'
            self.Tested = 'Tested'
            self.RegistrationVoid = 'Registration void'
            self.FormalExam = 'Formal exam'
            self.InformalExam = 'Informal exam'
            self.GenerateTestPaper = 'Generate test paper'
            self.ResetTestPaper = 'Reset test paper'
            self.TestPaperScoring = 'Test paper scoring'
            self.DataIntoHistory = 'Data into history'

            self.SubjectName = 'Subject name'
            self.SubjectStatus = 'Subject status'
            self.NewSubject = 'New subject'
            self.SubjectDetails = 'Subject details'
            self.SubjectCode = 'Subject code'

            self.KnowledgePointName = 'Knowledge point name'
            self.KnowledgePointStatus = 'Knowledge point status'
            self.NewKnowledgePoint = 'New knowledge point'
            self.KnowledgeDetails = 'Knowledge details'
            self.KnowledgePointCode = 'Knowledge point code'

        elif self.Type == 'zh-cn':
            self.ManagerLogin = '管理员登录'
            self.TeacherLogin = '教师登录'
            self.ExamineeLogin = '考生登录'
            self.Back = '返回'
            self.Exam = '考试'
            self.PracticeQuestions = '练习题'
            self.LoginStudentID = '使用您的学生证号码登录'
            self.LoginWithAdmission = '使用您的准考证号码登录'
            self.StudentIDNumber = '学生证号码'
            self.AdmissionTicketNumber = '准考证号码'
            self.Login = '登录'
            self.Start = '开始'
            self.ChooseExamSubjects = '选择考试科目'
            self.SelectTestQuestionType = '选择试题类型'
            self.MultipleChoiceQuestions = '单项选择题'
            self.TrueOrFalse = '判断题'
            self.MultipleChoices = '多项选择题'
            self.FillInTheBlank = '填空题'
            self.QuestionsAndAnswers = '问答题'
            self.ProgrammingQuestions = '编程题'
            self.DragAndDrop = '拖拽题'
            self.ConnectingQuestion = '连线题'

            self.ManageristratorAccount = '管理员账号'
            self.Password = '密码'
            self.Manager = '管理员'
            self.Teacher = '教师'
            self.Class = '班级'
            self.Examinee = '考生'
            self.RegistrationData = '报名'
            self.HistoryRegistration = '历史报名'
            self.Subject = '科目'
            self.KnowledgePoint = '知识点'
            self.Headline = '大标题'
            self.TestQuestion = '试题'
            self.TestPaper = '试卷'
            self.TestPaperRules = '试卷规则'
            self.AnswerSheet = '答题卡'
            self.SystemLog = '系统日志'
            self.ExamLog = '考试日志'
            self.Exit = '退出'
            self.CurrentPage = '当前页码'
            self.TotalPages = '总页码数'
            self.PreviousPage = '上一页'
            self.NextPage = '下一页'
            self.EnterPageNumber = '输入页码'
            self.EnterTheNumberOfLines = '输入行数'
            self.Search = '搜索'
            self.Confirm = '确认'
            self.Delete = '删除'
            self.Refresh = '刷新'
            self.Normal = '正常'
            self.Disable = '禁用'
            self.Disabled = '已禁用'
            self.CreationTime = '创建时间'
            self.UpdateTime = '更新时间'
            self.ChangePassword = '修改密码'
            self.Description = '描述信息'
            self.Yes = '是'
            self.No = '否'
            self.NoDataAvailable = '没有可用数据'
            self.Submit = '提交'
            self.OperationFailed = '操作失败'

            self.Name = '姓名'
            self.NewManager = '新建管理员'
            self.ManagerDetails = '管理员详情'
            self.ManagerStatus = '管理员状态'

            self.NewTeacher = '新建教师'
            self.TeacherDetails = '教师详情'
            self.TeacherStatus = '教师状态'
            self.TeacherAccount = '教师账号'

            self.ClassName = '班级名称'
            self.NewClass = '新建班级'
            self.ClassDetails = '班级详情'
            self.ClassCode = '班级代码'

            self.NewExaminee = '新建考生'
            self.Contact = '联系方式'
            self.ExamineeNo = '考生编号'
            self.ExamineeDetails = '考生详情'

            self.NewRegistration = '新建报名'
            self.ImportRegistration = '导入报名'
            self.RegistrationDetails = '报名详情'
            self.RegisterInformation = '报名信息'
            self.ExamNo = '准考证号'
            self.TotalScore = '总分'
            self.PassLine = '及格线'
            self.ActualScore = '实际得分'
            self.ExamDuration = '额定考试时长'
            self.StartTime = '考试开始时间'
            self.EndTime = '考试结束时间'
            self.ActualDuration = '实际考试时长'
            self.PassStatus = '通过状态'
            self.ExamState = '考试状态'
            self.ExamType = '考试类型'
            self.NoAnswerSheet = '没有答题卡'
            self.WaitForVerification = '待考'
            self.Tested = '已考'
            self.RegistrationVoid = '报名作废'
            self.FormalExam = '正式考试'
            self.InformalExam = '非正式考试'
            self.GenerateTestPaper = '生成试卷'
            self.ResetTestPaper = '重置试卷'
            self.TestPaperScoring = '试卷打分'
            self.DataIntoHistory = '数据转入历史'

            self.SubjectName = '科目名称'
            self.SubjectStatus = '科目状态'
            self.NewSubject = '新建科目'
            self.SubjectDetails = '科目详情'
            self.SubjectCode = '科目代码'

            self.KnowledgePointName = '知识点名称'
            self.KnowledgePointStatus = '知识点状态'
            self.NewKnowledgePoint = '新建知识点'
            self.KnowledgeDetails = '知识点详情'
            self.KnowledgePointCode = '知识点代码'

        else:
            self.ManagerLogin = ''
            self.TeacherLogin = ''
            self.ExamineeLogin = ''
            self.Back = ''
            self.Exam = ''
            self.PracticeQuestions = ''
            self.LoginStudentID = ''
            self.LoginWithAdmission = ''
            self.StudentIDNumber = ''
            self.AdmissionTicketNumber = ''
            self.Login = ''
            self.Start = ''
            self.ChooseExamSubjects = ''
            self.SelectTestQuestionType = ''
            self.MultipleChoiceQuestions = ''
            self.TrueOrFalse = ''
            self.MultipleChoices = ''
            self.FillInTheBlank = ''
            self.QuestionsAndAnswers = ''
            self.ProgrammingQuestions = ''
            self.DragAndDrop = ''
            self.ConnectingQuestion = ''

            self.ManageristratorAccount = ''
            self.Password = ''
            self.Manager = ''
            self.Teacher = ''
            self.Class = ''
            self.Examinee = ''
            self.RegistrationData = ''
            self.HistoryRegistration = ''
            self.Subject = ''
            self.KnowledgePoint = ''
            self.Headline = ''
            self.TestQuestion = ''
            self.TestPaper = ''
            self.TestPaperRules = ''
            self.AnswerSheet = ''
            self.SystemLog = ''
            self.ExamLog = ''
            self.Exit = ''
            self.CurrentPage = ''
            self.TotalPages = ''
            self.PreviousPage = ''
            self.NextPage = ''
            self.EnterPageNumber = ''
            self.EnterTheNumberOfLines = ''
            self.Search = ''
            self.Confirm = ''
            self.Delete = ''
            self.Refresh = ''
            self.Normal = ''
            self.Disable = ''
            self.Disabled = ''
            self.CreationTime = ''
            self.UpdateTime = ''
            self.ChangePassword = ''
            self.Description = ''
            self.Yes = ''
            self.No = ''
            self.NoDataAvailable = ''
            self.Submit = ''
            self.OperationFailed = ''

            self.Name = ''
            self.NewManager = ''
            self.ManagerDetails = ''
            self.ManagerStatus = ''

            self.NewTeacher = ''
            self.TeacherDetails = ''
            self.TeacherStatus = ''
            self.TeacherAccount = ''

            self.ClassName = ''
            self.NewClass = ''
            self.ClassDetails = ''
            self.ClassCode = ''

            self.NewExaminee = ''
            self.Contact = ''
            self.ExamineeNo = ''
            self.ExamineeDetails = ''

            self.NewRegistration = ''
            self.ImportRegistration = ''
            self.RegistrationDetails = ''
            self.RegisterInformation = ''
            self.ExamNo = ''
            self.TotalScore = ''
            self.PassLine = ''
            self.ActualScore = ''
            self.ExamDuration = ''
            self.StartTime = ''
            self.EndTime = ''
            self.ActualDuration = ''
            self.PassStatus = ''
            self.ExamState = ''
            self.ExamType = ''
            self.NoAnswerSheet = ''
            self.WaitForVerification = ''
            self.Tested = ''
            self.RegistrationVoid = ''
            self.FormalExam = ''
            self.InformalExam = ''
            self.GenerateTestPaper = ''
            self.ResetTestPaper = ''
            self.TestPaperScoring = ''
            self.DataIntoHistory = ''

            self.SubjectName = ''
            self.SubjectStatus = ''
            self.NewSubject = ''
            self.SubjectDetails = ''
            self.SubjectCode = ''

            self.KnowledgePointName = ''
            self.KnowledgePointStatus = ''
            self.NewKnowledgePoint = ''
            self.KnowledgeDetails = ''
            self.KnowledgePointCode = ''